export const FETCH_SUMMARY = "FETCH_SUMMARY";
export const FETCH_SUMMARY_BY_DAY = "FETCH_SUMMARY_BY_DAY";

export const SET_SINGLE_LANGUAGE = "SET_SINGLE_LANGUAGE";

export const SET_SINGLE_COUNTRY = "SET_SINGLE_COUNTRY";

export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const SUMMARY_BY_COUNTRY = "SUMMARY_BY_COUNTRY";
export const CLEAR_COUNTRY_FIELD = "CLEAR_COUNTRY_FIELD";
